server:
  port: 9998
spring:
  main:
    allow-bean-definition-overriding: true
  sharding:
    datasource:
      ds[0]:
        msName: ms_dc_sdk
        dcName: new_dc_sdk_Master
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/new_dc_sdk?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: root
        slaveDs[0]:
          dcName: new_dc_sdk_Slave
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://127.0.0.1:3306/slave_new_dc_sdk?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password: root
    ##ds[1]:
    ## names: ds1
    ## type: com.alibaba.druid.pool.DruidDataSource
    ## url: jdbc:mysql://127.0.0.1:3306/dc_sdk?serverTimezone=GMT%2B8&useSSL=false
  ##  username: root
  ##  password: root
shardingTable:
  enable: true
logging:
  level:
    com:
      hyc:
        dao: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  mapperScanner:
    basePackage: com.dc.game.shardingspringbootstarter.mapper